Fixes #49 backend to manage pending transactions
fibercrypto/FiberCryptoWallet pull request #103
Opened 2019-08-06 18:47 UTC by stdevRulo

2019-08-06 21:21 UTC, olemis commented
@stdevRulo conflicts with `develop` .

2019-08-08 19:12 UTC, olemis requested changes

2019-08-08 19:12 UTC, olemis commented on src/coin/skycoin/models/account.go
> +func (wlt RemoteWallet) ListTransactions() core.TransactionIterator {
Should be factored out into a new method defined in `CDryptoAccount` interface o be implemented in `RemoteWallet` .

2019-08-08 19:12 UTC, olemis commented on src/coin/skycoin/models/coin.go
> +  	return []string{"SKY", "SKYCH"}
use variaables in `params`

2019-08-08 19:12 UTC, olemis commented on src/coin/skycoin/models/coin.go
> +	Timestamp core.TransactionTimestamp
No fields . Just wrap Skycoin core (or readable) types so as to satisfy interface methods.

2019-08-28 01:06 UTC, olemis commented
@stdevRulo Travis failures . Pls fix before merge

2019-08-28 21:56 UTC, olemis requested changes

2019-08-28 21:56 UTC, olemis commented on src/coin/skycoin/models/account.go
> +func (wlt RemoteWallet) ListPendingTransactions() core.TransactionIterator {
This function should return an error on failure

2019-08-28 22:06 UTC, olemis requested changes

2019-08-28 22:06 UTC, olemis commented on src/coin/skycoin/models/coin.go
> +	//TODO: return err here
Return an error instance on failure

2019-08-28 23:25 UTC, olemis commented
@stdevMac can you take a look into this ? Travis failing

2019-09-05 02:01 UTC, olemis commented
@stdevRulo conflicts

2019-09-13 23:05 UTC, olemis requested changes
Use parameterized `AltcoinQuotient()` everywhere needed e.g.

```sh
$ grep -nr 1000000 src/
src//util/util.go:14:	return uint64(coin * 1000000), err
src//models/blockchainModels.go:42:	bs.infoRequester = *skycoin.NewSkycoinBlockchainStatus(1000000) //FIXME: set correct value
src//models/history/historyManager.go:177:				val = val / 1000000
src//models/history/historyManager.go:205:				val = val / 1000000
src//models/history/historyManager.go:213:				val = val / 1000000
```

2019-09-17 22:28 UTC, stdevRulo commented
> Use parameterized `AltcoinQuotient()` everywhere needed e.g.
> 
> ```shell
> $ grep -nr 1000000 src/
> src//util/util.go:14:	return uint64(coin * 1000000), err
> src//models/blockchainModels.go:42:	bs.infoRequester = *skycoin.NewSkycoinBlockchainStatus(1000000) //FIXME: set correct value
> src//models/history/historyManager.go:177:				val = val / 1000000
> src//models/history/historyManager.go:205:				val = val / 1000000
> src//models/history/historyManager.go:213:				val = val / 1000000
> ```

all fixed except
>```shell
> src//models/blockchainModels.go:42:	bs.infoRequester = *skycoin.NewSkycoinBlockchainStatus(1000000) //FIXME: set correct value
>```
Because it is not related with any coin value calculations

2019-09-18 23:02 UTC, olemis approved these changes

2019-09-18 23:03 UTC, merged