Address book
fibercrypto/FiberCryptoWallet pull request #265
Opened 2019-12-04 18:02 UTC by stdevHsequeda

Fixes #152 

**Changes:**
-Map (Address,coinName).
-Added data package.
-Testing AddressBook methods.
-Added AddressBook into Ui.
-Added selection from AddressBook in Transactions.
-Rejected invalid address.
-Added security type selection.

**Does this change need to mentioned in CHANGELOG.md?**
yes

**Requires testing**
Requires testing
yes

**Comments about testing , should you have some**

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +	Type1 = iota
The names of the cont `Type1`, `Type2` and `Type3` should say what really is, pls change the names

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +	errParseContact   = errors.New(" The inserted cannot be parse")
The inserted `what` ? please reformulate that error.

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +type DB struct {
Please create a interface `DataBase`, and in your code use the interface, in case we want in another moment interact with other DB. 
Here should be a implementation of this interface

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +func NewAddressBook(path string) (core.AddressBook, error) {
Here should pass to this function one instance of this Database that I told you

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +			logrus.Fatal(err)
Create a instance of our logger here, not use directly `logrus`

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +			return errorWrapper(errBucketEmpty)
In each returned error please make a log

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +	return e, err
`err` should be `nil` here

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +					return fmt.Errorf("Address with value: %s  and Cointype: %s alredy exist",
If you have a default errors, should be there and not create a new error. pls add this error to defaults

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +				return fmt.Errorf(" Contact with name: %s alredy exist", contact.(*Contact).Name)
Same with the defaults errors here

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +	if err := bConf.Put([]byte("hash"), hash); err != nil {
If possible, create constants for this words , example:
```golang
const = (
    Hash           = "hash"
    Entropy       = "entropy"
    sectionType = "secType"
)
```
But this with names according to functions

2019-12-10 22:39 UTC, stdevMac commented on src/data/addressbook.go
> +func (ab *DB) encryptAESGCM(c *Contact) ([]byte, error) {
Comment a little this function, and what is the meaning of `AESGCM`?

2019-12-10 22:39 UTC, stdevMac commented on src/ui/AddressBook.qml
> +// Resource imports
Also add commented the lines in case of we should need load delegates from the `qrc`

2019-12-19 20:50 UTC, stdevMac requested changes

2019-12-19 20:50 UTC, stdevMac commented on .gitignore
> -coverage.html
@stdevHsequeda why did you remove coverage files from gitignore?

2019-12-19 20:50 UTC, stdevMac commented on main.go
> +	app.SetApplicationName("FiberCrypto Wallet")
Pls roll back this changes

2019-12-19 21:42 UTC, stdevHsequeda commented
this could happen to me in a merge

2019-12-19 21:42 UTC, stdevHsequeda commented on main.go
> +	app.SetApplicationName("FiberCrypto Wallet")
this could happen to me in a merge

2019-12-20 00:39 UTC, stdevMac approved these changes

2019-12-21 22:34 UTC, merged