Unify generics code
fibercrypto/FiberCryptoWallet pull request #297
Opened 2019-12-24 03:11 UTC by stdevHsequeda

Fixes #290 

**Changes:**
-Added Iterator interface.
-Implementing Iterator interface in util packege with GenericIterator type.
- Replaced all old iterators implementation for GenericIterator.
-Added test and comments for GenericIterator type.

**Does this change need to mentioned in CHANGELOG.md?**
 no

**Requires testing**
Requires testing
 no

**Comments about testing , should you have some**

2019-12-24 03:18 UTC, olemis commented
@stdevHsequeda good , will take a look into this shortly

2019-12-24 05:04 UTC, olemis requested changes

2019-12-24 05:04 UTC, olemis commented on src/core/generic.go
> +	CurrentData(interface{}) error
This needs be changed

2019-12-24 05:10 UTC, stdevHsequeda commented on src/core/generic.go
> +	CurrentData(interface{}) error
To Value() interface?

2019-12-30 00:31 UTC, olemis commented on src/core/generic.go
> +	CurrentData(interface{}) error
yep

2020-01-22 23:44 UTC, olemis commented
I'm starting to hesitate about whether moving forward with this is a good idea

2020-02-10 00:11 UTC, olemis commented
I am not satisfied with the approaches I've seen so far ... Let's keep things the way they are now and reopen this should situation change at some point later

2020-02-10 00:11 UTC, closed without merging